### ISSUE TITLE
malt property does not appear

### ISSUE THREAD

**Issue by magicfever** [bnpr/Malt#120]
Hi I just know Malt and want to try but when I try to install, my malt menu is not same as tutorial - I do not have malt property.
( mac osx version )

here is my screen record how I install and how i do not have malt property
https://www.berrycast.com/conversations/307b8d90-9e86-52ac-a930-792d868e602e

here is my log

Blender > SETUP IOCapture
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51735)
Malt > Name: MESH Adress: ('127.0.0.1', 51736)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51737)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51738)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51739)
Malt > Name: RENDER Adress: ('127.0.0.1', 51740)
Blender > Traceback (most recent call last):

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 145, in depsgraph_update

Blender >     
Blender > scene.world.malt.update_pipeline(bpy.context)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 57, in update_pipeline

Blender >     
Blender > bridge = Bridge.Client_API.Bridge(path, debug_mode)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 85, in __init__

Blender >     
Blender > self.parameters = self.connections['PARAMS'].recv()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 255, in recv

Blender >     
Blender > buf = self._recv_bytes()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes

Blender >     
Blender > buf = self._recv(4)
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 388, in _recv

Blender >     
Blender > raise EOFError
Blender > 

Blender > EOFError
Blender > 
Blender > 

Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51747)
Malt > Name: MESH Adress: ('127.0.0.1', 51748)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51749)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51750)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51751)
Malt > Name: RENDER Adress: ('127.0.0.1', 51752)
Blender > Traceback (most recent call last):

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 145, in depsgraph_update

Blender >     
Blender > scene.world.malt.update_pipeline(bpy.context)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 57, in update_pipeline

Blender >     
Blender > bridge = Bridge.Client_API.Bridge(path, debug_mode)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 85, in __init__

Blender >     
Blender > self.parameters = self.connections['PARAMS'].recv()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 255, in recv

Blender >     
Blender > buf = self._recv_bytes()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes

Blender >     
Blender > buf = self._recv(4)
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 388, in _recv

Blender >     
Blender > raise EOFError
Blender > 

Blender > EOFError
Blender > 
Blender > 

Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51759)
Malt > Name: MESH Adress: ('127.0.0.1', 51760)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51761)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51762)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51763)
Malt > Name: RENDER Adress: ('127.0.0.1', 51764)
Blender > Traceback (most recent call last):

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 145, in depsgraph_update

Blender >     
Blender > scene.world.malt.update_pipeline(bpy.context)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 57, in update_pipeline

Blender >     
Blender > bridge = Bridge.Client_API.Bridge(path, debug_mode)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 85, in __init__

Blender >     
Blender > self.parameters = self.connections['PARAMS'].recv()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 255, in recv

Blender >     
Blender > buf = self._recv_bytes()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes

Blender >     
Blender > buf = self._recv(4)
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 388, in _recv

Blender >     
Blender > raise EOFError
Blender > 

Blender > EOFError
Blender > 
Blender > 

Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51771)
Malt > Name: MESH Adress: ('127.0.0.1', 51772)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51773)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51774)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51775)
Malt > Name: RENDER Adress: ('127.0.0.1', 51776)
Blender > Traceback (most recent call last):

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 145, in depsgraph_update

Blender >     
Blender > scene.world.malt.update_pipeline(bpy.context)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 57, in update_pipeline

Blender >     
Blender > bridge = Bridge.Client_API.Bridge(path, debug_mode)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 85, in __init__

Blender >     
Blender > self.parameters = self.connections['PARAMS'].recv()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 255, in recv

Blender >     
Blender > buf = self._recv_bytes()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes

Blender >     
Blender > buf = self._recv(4)
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 388, in _recv

Blender >     
Blender > raise EOFError
Blender > 

Blender > EOFError
Blender > 
Blender > 

Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51783)
Malt > Name: MESH Adress: ('127.0.0.1', 51784)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51785)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51786)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51787)
Malt > Name: RENDER Adress: ('127.0.0.1', 51788)
Blender > Traceback (most recent call last):

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 145, in depsgraph_update

Blender >     
Blender > scene.world.malt.update_pipeline(bpy.context)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 57, in update_pipeline

Blender >     
Blender > bridge = Bridge.Client_API.Bridge(path, debug_mode)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 85, in __init__

Blender >     
Blender > self.parameters = self.connections['PARAMS'].recv()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 255, in recv

Blender >     
Blender > buf = self._recv_bytes()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes

Blender >     
Blender > buf = self._recv(4)
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 388, in _recv

Blender >     
Blender > raise EOFError
Blender > 

Blender > EOFError
Blender > 
Blender > 

Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51795)
Malt > Name: MESH Adress: ('127.0.0.1', 51796)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51797)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51798)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51799)
Malt > Name: RENDER Adress: ('127.0.0.1', 51800)
Blender > Traceback (most recent call last):

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 145, in depsgraph_update

Blender >     
Blender > scene.world.malt.update_pipeline(bpy.context)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 57, in update_pipeline

Blender >     
Blender > bridge = Bridge.Client_API.Bridge(path, debug_mode)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 85, in __init__

Blender >     
Blender > self.parameters = self.connections['PARAMS'].recv()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 255, in recv

Blender >     
Blender > buf = self._recv_bytes()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes

Blender >     
Blender > buf = self._recv(4)
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 388, in _recv

Blender >     
Blender > raise EOFError
Blender > 

Blender > EOFError
Blender > 
Blender > 

Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51807)
Malt > Name: MESH Adress: ('127.0.0.1', 51808)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51809)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51810)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51811)
Malt > Name: RENDER Adress: ('127.0.0.1', 51812)
Blender > Traceback (most recent call last):

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 145, in depsgraph_update

Blender >     
Blender > scene.world.malt.update_pipeline(bpy.context)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 57, in update_pipeline

Blender >     
Blender > bridge = Bridge.Client_API.Bridge(path, debug_mode)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 85, in __init__

Blender >     
Blender > self.parameters = self.connections['PARAMS'].recv()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 255, in recv

Blender >     
Blender > buf = self._recv_bytes()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes

Blender >     
Blender > buf = self._recv(4)
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 388, in _recv

Blender >     
Blender > raise EOFError
Blender > 

Blender > EOFError
Blender > 
Blender > 

Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51819)
Malt > Name: MESH Adress: ('127.0.0.1', 51820)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51821)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51822)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51823)
Malt > Name: RENDER Adress: ('127.0.0.1', 51824)
Blender > Traceback (most recent call last):

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 145, in depsgraph_update

Blender >     
Blender > scene.world.malt.update_pipeline(bpy.context)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 57, in update_pipeline

Blender >     
Blender > bridge = Bridge.Client_API.Bridge(path, debug_mode)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 85, in __init__

Blender >     
Blender > self.parameters = self.connections['PARAMS'].recv()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 255, in recv

Blender >     
Blender > buf = self._recv_bytes()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes

Blender >     
Blender > buf = self._recv(4)
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 388, in _recv

Blender >     
Blender > raise EOFError
Blender > 

Blender > EOFError
Blender > 
Blender > 

Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51831)
Malt > Name: MESH Adress: ('127.0.0.1', 51832)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51833)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51834)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51835)
Malt > Name: RENDER Adress: ('127.0.0.1', 51836)
Blender > Traceback (most recent call last):

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 145, in depsgraph_update

Blender >     
Blender > scene.world.malt.update_pipeline(bpy.context)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 57, in update_pipeline

Blender >     
Blender > bridge = Bridge.Client_API.Bridge(path, debug_mode)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 85, in __init__

Blender >     
Blender > self.parameters = self.connections['PARAMS'].recv()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 255, in recv

Blender >     
Blender > buf = self._recv_bytes()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes

Blender >     
Blender > buf = self._recv(4)
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 388, in _recv

Blender >     
Blender > raise EOFError
Blender > 

Blender > EOFError
Blender > 
Blender > 

Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51843)
Malt > Name: MESH Adress: ('127.0.0.1', 51844)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51845)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51846)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51847)
Malt > Name: RENDER Adress: ('127.0.0.1', 51848)
Blender > Traceback (most recent call last):

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 145, in depsgraph_update

Blender >     
Blender > scene.world.malt.update_pipeline(bpy.context)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 57, in update_pipeline

Blender >     
Blender > bridge = Bridge.Client_API.Bridge(path, debug_mode)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 85, in __init__

Blender >     
Blender > self.parameters = self.connections['PARAMS'].recv()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 255, in recv

Blender >     
Blender > buf = self._recv_bytes()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes

Blender >     
Blender > buf = self._recv(4)
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 388, in _recv

Blender >     
Blender > raise EOFError
Blender > 

Blender > EOFError
Blender > 
Blender > 

Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51857)
Malt > Name: MESH Adress: ('127.0.0.1', 51858)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51859)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51860)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51861)
Malt > Name: RENDER Adress: ('127.0.0.1', 51862)
Blender > Traceback (most recent call last):

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltMaterial.py", line 21, in update_source

Blender >     
Blender > compiled_material = MaltPipeline.get_bridge().compile_material(path)
Blender > 

Blender > AttributeError
Blender > : 
Blender > 'NoneType' object has no attribute 'compile_material'
Blender > 

Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51869)
Malt > Name: MESH Adress: ('127.0.0.1', 51870)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51871)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51872)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51873)
Malt > Name: RENDER Adress: ('127.0.0.1', 51874)
Blender > Traceback (most recent call last):

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 145, in depsgraph_update

Blender >     
Blender > scene.world.malt.update_pipeline(bpy.context)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 57, in update_pipeline

Blender >     
Blender > bridge = Bridge.Client_API.Bridge(path, debug_mode)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 85, in __init__

Blender >     
Blender > self.parameters = self.connections['PARAMS'].recv()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 255, in recv

Blender >     
Blender > buf = self._recv_bytes()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes

Blender >     
Blender > buf = self._recv(4)
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 388, in _recv

Blender >     
Blender > raise EOFError
Blender > 

Blender > EOFError
Blender > 
Blender > 

Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51881)
Malt > Name: MESH Adress: ('127.0.0.1', 51882)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51883)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51884)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51885)
Malt > Name: RENDER Adress: ('127.0.0.1', 51886)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51893)
Malt > Name: MESH Adress: ('127.0.0.1', 51894)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51895)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51896)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51897)
Malt > Name: RENDER Adress: ('127.0.0.1', 51898)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51908)
Malt > Name: MESH Adress: ('127.0.0.1', 51909)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51910)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51911)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51912)
Malt > Name: RENDER Adress: ('127.0.0.1', 51913)
Blender > Traceback (most recent call last):

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 145, in depsgraph_update

Blender >     
Blender > scene.world.malt.update_pipeline(bpy.context)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/MaltPipeline.py", line 57, in update_pipeline

Blender >     
Blender > bridge = Bridge.Client_API.Bridge(path, debug_mode)
Blender > 

Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 85, in __init__

Blender >     
Blender > self.parameters = self.connections['PARAMS'].recv()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 255, in recv

Blender >     
Blender > buf = self._recv_bytes()
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes

Blender >     
Blender > buf = self._recv(4)
Blender > 

Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/multiprocessing/connection.py", line 388, in _recv

Blender >     
Blender > raise EOFError
Blender > 

Blender > EOFError
Blender > 
Blender > 

Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 51920)
Malt > Name: MESH Adress: ('127.0.0.1', 51921)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 51922)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 51923)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 51924)
Malt > Name: RENDER Adress: ('127.0.0.1', 51925)
Blender > Exception in module unregister():
Blender >  
Blender > '/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/quick_menu.py'
Blender > 

Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 438, in disable
    mod.unregister()

Blender > 
Blender >   File "/Users/numnim/Library/Application Support/Blender/2.93/scripts/addons/quick_menu.py", line 2062, in unregister
    for c in classes: bpy.util.unregister_class(c)

Blender > 
Blender > AttributeError: module 'bpy' has no attribute 'util'

Blender >

**Comment by pragma37** [comment]
Hi! Looks like GLFW is failing to initialize, but it's not reporting any error. I guess it's just crashing?
(GLFW is the library that Malt uses for creating a window and an OpenGL context)

I don't have access to a Mac at the moment, so I really can't do too much on my side.
Just for reference, what Mac hardware and OS version are you using?

**Comment by magicfever** [comment]
Hi! Pragma37, thanks for reply :)
I try same process in windows and I can use with no problem, so i think on mac may have problem with something~
and this is detail of my mac 
<img width="302" alt="Screen Shot 2021-09-10 at 00 29 51" src="https://user-images.githubusercontent.com/16503515/132734247-cc7ceb8d-5fcf-4595-a80e-d03798f254ab.png">

**Comment by pragma37** [comment]
Deleting this, since we no longer provide Mac support.
