### ISSUE TITLE
OpenGL Segfault on tab change in render mode

### ISSUE THREAD

**Issue by Lateasusual** [bnpr/Malt#36]
Linux, Nvidia drivers

Steps to reproduce:
 - Startup file
 - Change render engine to malt, change 3D view to render/lookdev (with/without any shaders loaded)
 - Click on any other tab in blender (may need to swap back and forth a few times)
 - Segmentation fault in graphics driver

It's not reproducible 100%, so it definitely seems like a race condition somewhere in blender. Not sure if there's anything we can do about it beer-side, just recording here since I haven't had a chance to dig deeper yet

Backtrace:
![image](https://user-images.githubusercontent.com/24512254/103444895-3f292100-4c65-11eb-9f3f-a292ddc3c121.png)

**Comment by pragma37** [comment]
The next big change I want to implement is running Malt on its own process.

Sharing OpenGL context with Blender has proven to be very troublesome and the source of almost every bug report so far.

The downside is that it will introduce some extra latency, but I think it worths it.

On the plus side, most OpenGL issues should go away, it will make Blender crashes almost impossible and Blender itself will stay responsive even if the render performance is slow.
It would also allow us to move to other graphics API in the future, like WebGPU.

**Comment by ABugNamedBeetle** [comment]
If you want to separate the two context, we can do what LuxRenderer or POV-ray does, and for to get some performance we can build the engine in C++, then there won't be the need of wrapper class. And for cross platform Qt is good.

**Comment by pragma37** [comment]
I'm closing this since with the new refactor the amount of GL code that runs on the Blender side is minimal.
