### ISSUE TITLE
Make render BG Transparent?

### ISSUE THREAD

**Issue by GOvEy1nw** [bnpr/Malt#40]
Hey. Is there a way to make the BG transparent on renders with BEER? The 'film' tab isn't available like it is in EEVEE so I can't set it there, nor does setting background color in 'world' settings to transparent work. Is this just not possible yet or am I missing a setting somewhere?

**Comment by pragma37** [comment]
Hi. It's not implemented yet.

It will be handled by setting the Background Color alpha.

**Comment by pragma37** [comment]
Fixed in 36fb537051be004a5d4ecb3cb7e37f0686e35650
