### ISSUE TITLE
Uniform Vector Arrays don't show up correctly in some cases

### ISSUE THREAD

**Issue by ZanyDreamer** [bnpr/Malt#52]
**Platform Description:**
**OS:** Windows 10
**CPU:** Ryzen 1600
**GPU:** Nvidia Geforce GTX 1060

**Blender Version:** 2.83
**Malt Version:** v1-beta _(latest as of now)_

**Problem Description:**
Assume we're using a _"const int n"_ as array size:
1. The variables display as if one large vector. _(vec(n*2) for vec2, for example)_
2. After loading the shader once, if 'n' is changed then the UI doesn't update to reflect it. _(The shader output does though)_
3. If vector type is changed, then the UI updates. Problem 1 persists.
4. Odd things happen if type is changed again. Sometimes it shows both the previous set of variables and the new together. Sometimes it's just a text field. Reverting the save file brings it back to the older set.

2, 3 and 4 do not happen if the array is isolated from my particular use case. I have attached 2 mesh.glsl files, one with just the array and one with my particular use case.
[VectorArrayIssueMalt.zip](https://github.com/bnpr/Malt/files/5866672/VectorArrayIssueMalt.zip)

**Comment by ZanyDreamer** [comment]
Thanks for taking the time to look at the issue! In my case, the first element is showing up as a text field:
![image](https://user-images.githubusercontent.com/42736884/105749072-f2392180-5f68-11eb-823e-7e0a951a16d3.png)

**Comment by pragma37** [comment]
If you send me the file I can take a look at it.

Does it happens on a new material too?

**Comment by ZanyDreamer** [comment]
Does not happen on a new material. It makes sense that there would be issues if I don't use a clean slate. Thanks for the help!
