### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by ElioMacho** [bnpr/Malt#53]
when installing the shader, get an error warning
<img width="571" alt="Captura de pantalla 2021-01-27 a las 8 42 07 p  m" src="https://user-images.githubusercontent.com/57139710/106044574-326ee000-60e0-11eb-9c6f-1dbd54a0dc5d.png">
blender 2.91.2
iMac Retin 5k 27" 4ghz intel Core i7. 16gb memory

**Comment by pragma37** [comment]
Hi!
Sorry, but either your computer or (more likely) your OpenGL drivers don't meet the minimum requirements.

See #28 for reference.
