### ISSUE TITLE
Can't assign shader in Mac OSX

### ISSUE THREAD

**Issue by kurisutofu** [bnpr/Malt#56]
Hi,

I just installed Malt with blender 2.91 on mac OSX Big Sur and when choosing the shader source, in the material pane, I get the error below (Sorry it's a screenshot as I could not find a way to copy the text):

![Screen Shot 2021-02-02 at 22 58 34](https://user-images.githubusercontent.com/742894/106610898-a7dc2400-65aa-11eb-826d-f558b80b6819.png)

I'm also attaching the system info exported from blender.

[system-info.txt](https://github.com/bnpr/Malt/files/5911620/system-info.txt)

**Comment by BlenderNPR** [comment]
This is the same issue as #28

**Comment by kurisutofu** [comment]
> This is the same issue as #28

Sorry, I hadn't noticed that one ... I'll close this.
