### ISSUE TITLE
samplerCube and sampler3D don't seem to work?

### ISSUE THREAD

**Issue by friedererdmann** [bnpr/Malt#6]
Hey!

I've been trying to see if I can use cubemaps and other kind of textures in Malt, but adding a samplerCube or sampler3D doesn't seem to work. The UI falls back on an integer selector instead of a file selector. Is there a chance to support these? Or even to sample the Blender viewport's current IBL as well?

Thanks!

**Comment by msmshazan** [comment]
Any container which supports these formats
![image](https://user-images.githubusercontent.com/20334207/101273811-bd0d2000-37be-11eb-84ce-9de8fb935295.png)

source : https://docs.unity3d.com/Manual/class-TextureImporterOverride.html

**Comment by pragma37** [comment]
@msmshazan Answered you in #21 

Regarding the original issue. I added an hdri_uv function that takes a normal vector and returns the equivalent equirectangular projection uv (the one used by hdri maps).

Hopefully that covers most use cases. If it doesn't I'm open for feedback.
