### ISSUE TITLE
Low framerate in viewport (v1.0 refactor)

### ISSUE THREAD

**Issue by tonpix** [bnpr/Malt#61]
https://drive.google.com/file/d/1bAuDSxqQoYKSmypCj1BxG3Yu6uryMCoO/view?usp=sharing

Open .blend, rotate around

Clip demo: https://streamable.com/8s0z38 (not best clip framerate to showcase issue, but mouse cursor is smooth, while viewport seems to have like 10-20 fps)

**Comment by pragma37** [comment]
Is the performance worse than in the beta branch?

**Comment by tonpix** [comment]
> Is the performance worse than in the beta branch?

It's worse, yes. Beta had a smooth viewport (6.3MB addon size) - tested again just now https://streamable.com/sypl2n

**Comment by tonpix** [comment]
I confirm with simplified .blend file that beta (6.7MB) is smooth compared to refactor (7.3MB)

**Comment by pragma37** [comment]
I get about 30fps on your blend file on a GTX 950, so a 1080 shouldn't have any trouble even at those settings.

Please, download the latest build and follow these steps:
1. In the BlenderMalt addon preferences panel enable *Debug Mode*.
2. Switch the viewport to render mode.
3. Move the viewport camera.
4. Go back to the addon preferences panel and click on Open Session Log.
5. Attach the log file to this issue.
6. Don't forget to disable the Debug Mode!

**Comment by tonpix** [comment]
Sure, but I'm a bit confused with steps - can't find debug option and with latest build, do you mean Malt? I've noticed the latest I can find on github is v1-beta from 3 days ago and there's no v1-refactor which was more recent than beta. With v1-refactor/7.3MB addon, this is how addon preferences look 
![image](https://user-images.githubusercontent.com/13473971/109164735-0dbb6600-777b-11eb-90ea-2182cfcdecaa.png)

**Comment by pragma37** [comment]
I mean the latest build of the refactor branch:
https://github.com/bnpr/Malt/releases/tag/v1-refactor

**Comment by tonpix** [comment]
Thanks, there's session log (simplified .blend was opened after installing/activating latest addon build):
[malt 2021-02-25(15-26).log](https://github.com/bnpr/Malt/files/6043631/malt.2021-02-25.15-26.log)

**Comment by pragma37** [comment]
The performance is certainly much worse than it should be, and it also seems very inconsistent (some frames take less than 16ms, others over 100ms).
My guess is that it's related to the OS or the GPU drivers priority.

I updated the refactor branch to manually increase the process priority.
So try downloading the latest build and see if that helps.

If it doesn't you'll have to rely on lowering your scene render settings:
https://github.com/bnpr/Malt/tree/pre-release-refactor#first-steps
Or maybe increase them to see if that helps?

Is this a laptop? Could it be related to energy settings?
Do you maybe have some kind of software that could interfere? Overclocking or some gaming overlay?
You could also try to restore your Nvidia driver settings to default values in case you have changed them.

**Comment by pragma37** [comment]
@tonpix Did you have time to test this?

**Comment by tonpix** [comment]
My apologies for not replying back then, I've actually tested quickly after your suggestions from 25th Feb and, if I remember correctly :

- tried the updated branch with increased priotity - didn't help
- it wasn't laptop, just stationary PC
- as for software interference, I had MSI afterburner (for downclocking memory/core clocks by 100MHz on GTX1080) and Argus monitor (for monitoring/logging temps). I think I closed those apps and didn't see changes in perf
- no custom global settings in nvidia panel

Then went silent for months after those tests, sorry! But I've tried again newest Malt week ago with blender 2.92/2.93. It was much better - the framerate difference between Malt renderer and Eevee was smaller, around 20-40% I think? And there was slight desync between viewport outlines and 3D models, by few frames. If I remember, these numbers are expected (or were expected few months ago at least), so if technical expectations still stand up, then Malt is working as expected :) Thank you for again for trying to help, sorry again for going silent, some personal stuff happened.

**Comment by pragma37** [comment]
Thank you for reporting. I'm glad to know the problem is fixed now.

Malt now ships with a custom python version that sets some flags to asks graphics drivers to run in high-performance profile.
It's used to prevent the application from running in the integrated GPU, but I guess it can also affect performance when running on the dedicated GPU?
At least that would be my bet.
