### ISSUE TITLE
Glitchy lines after not applying scale

### ISSUE THREAD

**Issue by TahsinTariq** [bnpr/Malt#70]
Discussion started here: https://github.com/bnpr/Malt/discussions/63#discussioncomment-429726

Applying level 1 subdiv on cube:
![image](https://user-images.githubusercontent.com/62146852/111442079-30192180-8732-11eb-9610-60a27890900d.png)

Scaling on y axis but not applying scale and moving around the viewport:
![image](https://user-images.githubusercontent.com/62146852/111442394-84240600-8732-11eb-8b45-daa0af0bca88.png)

Applying scale:
![image](https://user-images.githubusercontent.com/62146852/111442937-15937800-8733-11eb-964b-829685f8e667.png)

Other than adding the sun light and making the lines thicker in an advanced_line material, nothing else was changed.

Here's the blend file without the scale applied: 
[glitchy_lines.zip](https://github.com/bnpr/Malt/files/6155060/glitchy_lines.zip)

**Comment by pragma37** [comment]
Fixed in 436f510d8e81a354444cf2306bb0c05e4023fd9c

Thank you for the report and the blend file.
