### ISSUE TITLE
Render Tab doesn't fully load. Drags around.

### ISSUE THREAD

**Issue by virtualvessels** [bnpr/Malt#79]
Hello. For some reason, Malt's render tab isn't working right. Need some help.

--------------------------------------------------------------------------------
[system-info.txt](https://github.com/bnpr/Malt/files/6288351/system-info.txt)

--------------------------------------------------------------------------------------------------
Info: Deleted 1 object(s)

SETUP IOCapture
Unable to load numpy_formathandler accelerator from OpenGL_accelerate
Blender 2.91.2 b'master' b'5be9ef417703'
Info: Total files 0 | Changed 0 | Failed 0
OpenCL error: CL_INVALID_VALUE in __clewGetDeviceInfo(device_id, 0x1030, sizeof(data), &data, NULL) (C:\b\buildbot-worker-windows\windows_291\blender.git\intern\cycles\device\device_opencl.cpp:211)
fake_module: addon missing 'bl_info' gives bad performance!:

'C:\\Users\\Neotr\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons\\CustomPipeline.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Neotr\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons\\CustomPipeline.py'

fake_module: addon missing 'bl_info' gives bad performance!:

'C:\\Users\\Neotr\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons\\auto_load.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Neotr\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons\\auto_load.py'

fake_module: addon missing 'bl_info' gives bad performance!:

'C:\\Users\\Neotr\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons\\fspy.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Neotr\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons\\fspy.py'
--------------------------------------------------------------------------------------------------
Here's a video showing the problem with the render tab: https://streamable.com/fr1rua
Also the Blend File: https://drive.google.com/file/d/1m7ONqaDStB84SWVaL8LLDecku4FA0dgv/view?usp=sharing

**Comment by pragma37** [comment]
Could you attach the log file?
https://github.com/bnpr/Malt#bug-reports

Is this a laptop?

I had a similar issue at some point because the Malt process was getting very low priority.

**Comment by virtualvessels** [comment]
> Could you attach the log file?
> https://github.com/bnpr/Malt#bug-reports
> 
> Is this a laptop?
> 
> I had a similar issue at some point because the Malt process was getting very low priority.

Sure, here's the log file. 
[malt 2021-04-09(18-38).log](https://github.com/bnpr/Malt/files/6288793/malt.2021-04-09.18-38.log)

And indeed so, I'm running this off from a laptop.

**Comment by pragma37** [comment]
The problem is that Malt is using the integrated Intel GPU instead of the Nvidia RTX.
I can't fix that from the addon itself.

Could you test if this works for you?

- Go to your Blender installation folder. (By default *C:\Program Files\Blender Foundation\Blender 2.92*)
- From there go to *2.92 > python > bin*.
- That folder should contain 2 files: *python.exe* and *python37.dll*.
- Rename *python.exe* to something else, for example, *python-orgininal.exe*.
- Paste the *python.exe* [from this zip](https://github.com/bnpr/Malt/files/6230849/python.zip) into that folder.
- Open *Blender*, switch the renderer to *Malt* and attach the Log file as before.

If this works I can make this process automatic for the user.

**Comment by virtualvessels** [comment]
It's working fine for me now! If I notice something else, I'm sure to put in another issue, haha. Thank you so much, Pragma.
