### ISSUE TITLE
Not Showing Material Settings

### ISSUE THREAD

**Issue by lPegol** [bnpr/Malt#83]
After Installing BEER and using the Malt Engine every time i try to add a material or shader it just shows Malt Settings.

**Comment by pragma37** [comment]
Hello!

Sorry, I'm not sure what do you mean. Specifically, what settings are you missing?

**Comment by lPegol** [comment]
> Hello!
> 
> Sorry, I'm not sure what do you mean. Specifically, what settings are you missing?
The Material Settings for when you're adding a shader it only displays Malt Settings and Viewport Display.

**Comment by pragma37** [comment]
> The Material Settings for when you're adding a shader it only displays Malt Settings and Viewport Display.

But are they empty or something? Could you post a screenshot?


Maybe you were expecting to see the EEVEE/Cycles settings there too? That's not how it works, each engine uses its own settings.

**Comment by lPegol** [comment]
![Unfortunate](https://user-images.githubusercontent.com/85026390/120243904-56fbe400-c29b-11eb-8867-d337a20fb21d.PNG)
![Very Unfortunate](https://user-images.githubusercontent.com/85026390/120243907-582d1100-c29b-11eb-9d90-d078e4b05347.PNG)

**Comment by lPegol** [comment]
this is all i seem to get.

**Comment by pragma37** [comment]
The only thing missing there are the Light Groups settings. What happens when you select a shader source, still no settings?

Please select a shader source and post your log file.
https://github.com/bnpr/Malt#bug-reports

**Comment by lPegol** [comment]
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55096)
Malt > Name: MESH Adress: ('127.0.0.1', 55097)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55098)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55099)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55100)
Malt > Name: RENDER Adress: ('127.0.0.1', 55101)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55108)
Malt > Name: MESH Adress: ('127.0.0.1', 55109)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55110)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55111)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55112)
Malt > Name: RENDER Adress: ('127.0.0.1', 55113)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55121)
Malt > Name: MESH Adress: ('127.0.0.1', 55122)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55123)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55124)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55125)
Malt > Name: RENDER Adress: ('127.0.0.1', 55126)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55133)
Malt > Name: MESH Adress: ('127.0.0.1', 55134)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55135)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55136)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55137)
Malt > Name: RENDER Adress: ('127.0.0.1', 55138)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55145)
Malt > Name: MESH Adress: ('127.0.0.1', 55146)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55147)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55148)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55149)
Malt > Name: RENDER Adress: ('127.0.0.1', 55150)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55157)
Malt > Name: MESH Adress: ('127.0.0.1', 55158)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55159)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55160)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55161)
Malt > Name: RENDER Adress: ('127.0.0.1', 55162)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55169)
Malt > Name: MESH Adress: ('127.0.0.1', 55170)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55171)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55172)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55173)
Malt > Name: RENDER Adress: ('127.0.0.1', 55174)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55181)
Malt > Name: MESH Adress: ('127.0.0.1', 55182)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55183)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55184)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55185)
Malt > Name: RENDER Adress: ('127.0.0.1', 55186)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55193)
Malt > Name: MESH Adress: ('127.0.0.1', 55194)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55195)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55196)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55197)
Malt > Name: RENDER Adress: ('127.0.0.1', 55198)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55205)
Malt > Name: MESH Adress: ('127.0.0.1', 55206)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55207)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55208)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55209)
Malt > Name: RENDER Adress: ('127.0.0.1', 55210)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55217)
Malt > Name: MESH Adress: ('127.0.0.1', 55218)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55219)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55220)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55221)
Malt > Name: RENDER Adress: ('127.0.0.1', 55222)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55229)
Malt > Name: MESH Adress: ('127.0.0.1', 55230)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55231)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55232)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55233)
Malt > Name: RENDER Adress: ('127.0.0.1', 55234)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55245)
Malt > Name: MESH Adress: ('127.0.0.1', 55246)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55247)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55248)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55249)
Malt > Name: RENDER Adress: ('127.0.0.1', 55250)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55257)
Malt > Name: MESH Adress: ('127.0.0.1', 55258)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55259)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55260)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55261)
Malt > Name: RENDER Adress: ('127.0.0.1', 55262)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55269)
Malt > Name: MESH Adress: ('127.0.0.1', 55270)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55271)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55272)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55273)
Malt > Name: RENDER Adress: ('127.0.0.1', 55274)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55281)
Malt > Name: MESH Adress: ('127.0.0.1', 55282)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55283)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55284)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55285)
Malt > Name: RENDER Adress: ('127.0.0.1', 55286)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55293)
Malt > Name: MESH Adress: ('127.0.0.1', 55294)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55295)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55296)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55297)
Malt > Name: RENDER Adress: ('127.0.0.1', 55298)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55305)
Malt > Name: MESH Adress: ('127.0.0.1', 55306)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55307)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55308)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55309)
Malt > Name: RENDER Adress: ('127.0.0.1', 55310)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55317)
Malt > Name: MESH Adress: ('127.0.0.1', 55318)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55319)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55320)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55321)
Malt > Name: RENDER Adress: ('127.0.0.1', 55322)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55329)
Malt > Name: MESH Adress: ('127.0.0.1', 55330)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55331)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55332)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55333)
Malt > Name: RENDER Adress: ('127.0.0.1', 55334)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55341)
Malt > Name: MESH Adress: ('127.0.0.1', 55342)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55343)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55344)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55345)
Malt > Name: RENDER Adress: ('127.0.0.1', 55346)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55355)
Malt > Name: MESH Adress: ('127.0.0.1', 55356)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55357)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55358)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55359)
Malt > Name: RENDER Adress: ('127.0.0.1', 55360)

**Comment by pragma37** [comment]
Looks like GLFW fails to initialize, but there's not any related error.

Turns out PyGLFW doesn't report errors by default.

I enabled them, so please download the latest build and post the log again.
It should report more useful info.

**Comment by lPegol** [comment]
Here you go.


Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55666)
Malt > Name: MESH Adress: ('127.0.0.1', 55667)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55668)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55669)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55670)
Malt > Name: RENDER Adress: ('127.0.0.1', 55671)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55678)
Malt > Name: MESH Adress: ('127.0.0.1', 55679)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55680)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55681)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55682)
Malt > Name: RENDER Adress: ('127.0.0.1', 55683)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55690)
Malt > Name: MESH Adress: ('127.0.0.1', 55691)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55692)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55693)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55694)
Malt > Name: RENDER Adress: ('127.0.0.1', 55695)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55702)
Malt > Name: MESH Adress: ('127.0.0.1', 55703)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55704)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55705)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55706)
Malt > Name: RENDER Adress: ('127.0.0.1', 55707)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55714)
Malt > Name: MESH Adress: ('127.0.0.1', 55715)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55716)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55717)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55718)
Malt > Name: RENDER Adress: ('127.0.0.1', 55719)
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: PARAMS Adress: ('127.0.0.1', 55726)
Malt > Name: MESH Adress: ('127.0.0.1', 55727)
Malt > Name: MATERIAL Adress: ('127.0.0.1', 55728)
Malt > Name: TEXTURE Adress: ('127.0.0.1', 55729)
Malt > Name: GRADIENT Adress: ('127.0.0.1', 55730)
Malt > Name: RENDER Adress: ('127.0.0.1', 55731)

**Comment by pragma37** [comment]
Really??? Honestly, I have no idea what could be going on.

It just seems like something is completely blocking the process. There are no errors or anything.
What are your PC specs (OS, hardware, Blender version) ? Do you have an anti-virus?
