### ISSUE TITLE
Broken link in malt material doc

### ISSUE THREAD

**Issue by BlenderNPR** [bnpr/Malt#84]
This location 
https://github.com/bnpr/Malt/tree/master/BlenderMalt#materials

The correct link for ​_MaltMaterials_ should be 
https://github.com/bnpr/Malt/blob/master/BlenderMalt/MaltMaterial.py

**Comment by pragma37** [comment]
Fixed in 58d2a914ae91b651f3f5028b93143858b692c123.
I also updated the outdated parts of the doc.

Thanks for the report!
