### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tiga2904** [bnpr/Malt#85]
error enabling malt add on .
 ModuleNotFoundError: No module named 'OpenGL'

**Comment by tiga2904** [comment]
can you give me malt v-1 beta ?

**Comment by pragma37** [comment]
That's strange, what version did you download?

> can you give me malt v-1 beta ?

I'm not sure what you mean. You can get it from the Release page:
https://github.com/bnpr/Malt/releases/tag/v1-beta
